### ISSUE TITLE
does it work with ajax

### ISSUE THREAD

**Issue by derhuerst** [briansteffens/github-streaks#1]
it looks like it doesn't work with the ajax-like partial loading. the streak counter doesn't show up.

**Comment by briansteffens** [comment]
Hmm, not sure, I didn't know ajax had anything to do with this page. Are you just going to a user profile page (like https://www.github.com/derhuerst) or is it some other view?

**Comment by derhuerst** [comment]
I went to https://github.com/derhuerst?tab=repositories and then clicked "contributions", which makes a blue loading indicator show up at the top of the page. I guess it's Ajax, since it's loading the content without reloading.

**Comment by briansteffens** [comment]
Oh I understand now, I'll take a closer look at this later. Thanks for letting me know!

**Comment by briansteffens** [comment]
Should be fixed now in the latest version, closing.
